// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClaaSY6WlKRifidmMZEZr88EnB8lxzv4',
    appId: '1:572647596772:web:a3cee187e6df9574ea02f1',
    messagingSenderId: '572647596772',
    projectId: 'mentor-match-640bc',
    authDomain: 'mentor-match-640bc.firebaseapp.com',
    storageBucket: 'mentor-match-640bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEBfO4FfuRZA8PRatb7uKSMidCWpJR2OA',
    appId: '1:572647596772:android:b0786d082ed22c28ea02f1',
    messagingSenderId: '572647596772',
    projectId: 'mentor-match-640bc',
    storageBucket: 'mentor-match-640bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWn5eehs_MupaKHZOv9KI-tGlONAuHiQ',
    appId: '1:572647596772:ios:f3694051afb0ad65ea02f1',
    messagingSenderId: '572647596772',
    projectId: 'mentor-match-640bc',
    storageBucket: 'mentor-match-640bc.appspot.com',
    iosBundleId: 'com.c25kenneth.mentorMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOWn5eehs_MupaKHZOv9KI-tGlONAuHiQ',
    appId: '1:572647596772:ios:cc06ba09fc5f1c51ea02f1',
    messagingSenderId: '572647596772',
    projectId: 'mentor-match-640bc',
    storageBucket: 'mentor-match-640bc.appspot.com',
    iosBundleId: 'com.example.mentorMatch.RunnerTests',
  );
}
